/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsComponentIdRouteImport } from './routes/components.$componentId'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthCallbackRouteImport } from './routes/_auth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsComponentIdRoute = ComponentsComponentIdRouteImport.update({
  id: '/components/$componentId',
  path: '/components/$componentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/_auth/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof AuthCallbackRoute
  '/sign-in': typeof AuthSignInRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof AuthCallbackRoute
  '/sign-in': typeof AuthSignInRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth/callback': typeof AuthCallbackRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/callback' | '/sign-in' | '/components/$componentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/callback' | '/sign-in' | '/components/$componentId'
  id:
    | '__root__'
    | '/'
    | '/_auth/callback'
    | '/_auth/sign-in'
    | '/components/$componentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSignInRoute: typeof AuthSignInRoute
  ComponentsComponentIdRoute: typeof ComponentsComponentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$componentId': {
      id: '/components/$componentId'
      path: '/components/$componentId'
      fullPath: '/components/$componentId'
      preLoaderRoute: typeof ComponentsComponentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/callback': {
      id: '/_auth/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSignInRoute: AuthSignInRoute,
  ComponentsComponentIdRoute: ComponentsComponentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
