/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsComponentIdRouteImport } from './routes/components.$componentId'
import { Route as ComponentsComponentIdEditRouteImport } from './routes/components.$componentId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsComponentIdRoute = ComponentsComponentIdRouteImport.update({
  id: '/components/$componentId',
  path: '/components/$componentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsComponentIdEditRoute = ComponentsComponentIdEditRouteImport.update({
  id: '/components/$componentId/edit',
  path: '/components/$componentId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
  '/components/$componentId/edit': typeof ComponentsComponentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
  '/components/$componentId/edit': typeof ComponentsComponentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
  '/components/$componentId/edit': typeof ComponentsComponentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/components/$componentId' | '/components/$componentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/components/$componentId' | '/components/$componentId/edit'
  id: '__root__' | '/' | '/components/$componentId' | '/components/$componentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsComponentIdRoute: typeof ComponentsComponentIdRoute
  ComponentsComponentIdEditRoute: typeof ComponentsComponentIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$componentId': {
      id: '/components/$componentId'
      path: '/components/$componentId'
      fullPath: '/components/$componentId'
      preLoaderRoute: typeof ComponentsComponentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$componentId/edit': {
      id: '/components/$componentId/edit'
      path: '/components/$componentId/edit'
      fullPath: '/components/$componentId/edit'
      preLoaderRoute: typeof ComponentsComponentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsComponentIdRoute: ComponentsComponentIdRoute,
  ComponentsComponentIdEditRoute: ComponentsComponentIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
